---
- name: Restart prometheus
  service: name=prometheus state=restarted enabled=yes

- name: Restart grafana
  service: name=grafana-server state=restarted enabled=yes

- name: Restart cron
  service: name=cron state=restarted enabled=yes
