---
## General

jmx_exporter_version: 0.3.0

## Service options

# Owner
jmx_exporter_user: prometheus
jmx_exporter_group: prometheus

# start on boot
jmx_exporter_service_enabled: True
# current state: started, stopped
jmx_exporter_service_state: started

# Files & Paths
jmx_exporter_root_directory: /opt/jmx_exporter

jmx_exporter_jar_path: "{{ jmx_exporter_root_directory }}/{{ jmx_exporter_jar_file }}"

jmx_exporter_conf_directory: /etc/jmx_exporter
jmx_exporter_conf_file: "jmx_config.yml"
jmx_exporter_conf_path: "{{ jmx_exporter_conf_directory }}/{{ jmx_exporter_conf_file }}"

jmx_exporter_log_directory: /var/log/jmx_exporter
jmx_exporter_log_file: "jmx_exporter.log"
jmx_exporter_log_path: "{{ jmx_exporter_log_directory }}/{{ jmx_exporter_log_file }}"

jmx_exporter_classpath_entries: []
#  - jar_path_1
#  - jar_path_2
#  - ...

jmx_exporter_config_template_path: "{{ playbook_dir }}/templates/jmx_exporter/config"

# Ports
jmx_exporter_port: 9110
jmx_exporter_internal_port: 5555

# JVM
jmx_exporter_xmx: 32m
jmx_exporter_xms: 32m

## This should be true if you want to debug with Vagrant and Jconsole
jmx_rmi: False
