---

# Needed to refer to other nodes (using hostvars) during serial execution
- name: Create inventory for nodes
  hosts: datanodes
 # remote_user: "{{remote_user}}"
 # become: true
 # become_method: sudo
 # become_user: root
 # tags: "data-node"
 # tasks:
#    - setup:

#- name: Setup data nodes
#  hosts: datanodes
#  remote_user: "{{remote_user}}"
#  sudo: True
#  roles:
#    - { role: data-node, tags: ['data-node']  }
#    - { role: check-mk, tags: ['check-mk'] }

# Needed to refer to other nodes (using hostvars) during serial execution
#- name: Create inventory for nodes
#  hosts: clusternodes
#  remote_user: "{{remote_user}}"
#  become: true
#  become_method: sudo
#  become_user: root
#  tags: "cluster-node"
#  tasks:
#    - setup:

#- name: Setup cluster nodes
#  hosts: clusternodes
#  serial: 1
#  remote_user: "{{remote_user}}"
#  become: true
#  become_method: sudo
#  become_user: root
#  roles:
#    - { role: cluster-node, tags: ['cluster-node'] }
#    - { role: check-mk, tags: ['check-mk'] }
#    - { role: nginx, tags: ['nginx'] }

- name: Setup base cluster nodes
  hosts: generic-cluster-nodes
  roles:
   - { role: rsyslog-source, tags: ['rsyslog-source'] }

- name: Setup log aggregation server
  hosts: log-server
  roles:
   - { role: rsyslog-sink, tags: ['rsyslog-sink'] }

- name: Setup Kafka nodes
  hosts: kafka-nodes
  roles:
   - { role: mesos-kafka, tags: ['kafka']}

- name: Prometheus node exporter
  hosts: local
  roles:
   - role: prometheus-node-exporter
     tags: ['prometheus-node-exporter']
     prometheus_node_exporter_version: 0.15.1
     prometheus_node_exporter_enabled_collectors:
       - cpu
       - diskstats
       - entropy
       - filesystem
       - loadavg
       - meminfo
     prometheus_node_exporter_config_flags:
       'web.listen-address': '0.0.0.0:9100'
       'log.level': 'info'

- name: Prometheus JMX exporter
  hosts: mesos-slaves
  roles:
   - role: prometheus-jmx-exporter
     tags: ['prometheus-jmx-exporter']

- name: Metric proxy
  hosts: local
  roles:
   - role: prometheus-metric-proxy
     tags: ['prometheus-metric-proxy']
