---
- name: Copy Nginx metric generator script
  copy:
    src: "opt/prometheus/make_prometheus_config.py"
    dest: "/opt/prometheus/make_prometheus_config.py"
    owner: "root"
    mode: 0700

- name: Create cron to generate configs
  cron:
    name: "Remove XML's Iberia streamer after 30 days"
    user: "root"
    job: "/opt/prometheus/refresh_prometheus_config.sh"
    cron_file: nginx-metrics-proxy
