---

- name: Copy Prometheus metric generator script
  copy:
    src: "etc/yum.repos.d/prometheus.repo"
    dest: "/etc/yum.repos.d/prometheus.repo"
    owner: "root"
    mode: 0700

- name: Install monitoring packages
  yum:
    name="{{ item }}"
    state=latest
    update_cache=yes
  with_items:
    - prometheus
    - grafana-server

- name: Copy Prometheus metric generator script
  copy:
    src: "opt/prometheus/make_prometheus_config.py"
    dest: "/opt/prometheus/make_prometheus_config.py"
    owner: "root"
    mode: 0700

- name: Copy Prometheus cron script
  copy:
    src: "opt/prometheus/refresh_prometheus_config.sh"
    dest: "/opt/prometheus/refresh_prometheus_config.sh"
    owner: "root"
    mode: 0700

- name: Create cron job to generate configs
  cron:
    name: "Prometheus config update"
    user: "root"
    job: "/opt/prometheus/refresh_prometheus_config.sh"
    cron_file: nginx-metrics-proxy
