- include: systemtweaks.yml
- include: repositories.yml
- include: data-directories.yml
- include: packages.yml
- include: postgres-common.yml
- include: master.yml
  when: postgres_role is defined and postgres_role == "master"
- include: slave.yml
  when: postgres_role is defined and postgres_role == "slave"
