- ini_file:
    path: /etc/systemd/system/multi-user.target.wants/postgresql-9.6.service
    section: Unit
    option: After
    value: "syslog.target network.target network-online.target"
    no_extra_spaces: yes
  notify: Reload systemd

- name: Authentication file for pg_basebackup
  template: src=var/lib/pgsql/.pgpass.j2 dest=/var/lib/pgsql/.pgpass owner="{{ postgresql_admin_user }}" group="{{ postgresql_admin_user }}" mode=0600

- name: Set permissions for data directory
  file: 
    path="{{ postgresql_data_dir }}/9.6/data"
    state=directory
    owner="{{ postgresql_admin_user }}" 
    group="{{ postgresql_admin_user }}" 
    mode=0700

- name: Set permissions for log directory (needed for logwatch)
  file:
    path="/var/log/postgresql"
    state=directory
    owner="{{ postgresql_admin_user }}" 
    group="{{ postgresql_admin_user }}" 
    mode=0755

