- name: Reload postgres
  service: name=postgresql-9.6.service state=reloaded

- name: Restart postgres
  service: name=postgresql-9.6.service state=restarted

- name: Reload systemd
  command: systemctl daemon-reload
