---

galaxy_info:
  company: Idealista S.A.U.
  description: Prometheus JMX exporter
  min_ansible_version: 2.3.1.0
  license: Apache 2.0
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
  categories:
    - monitoring
