---
#- name: Install libselinux as prerequisite for SELinux Ansible module
#  yum:
#    name: "{{item}}"
#    state: latest
#  with_items:
#    - libselinux-python
#    - libsemanage-python
#
#- name: Disable SELinux at next reboot
#  selinux:
#    state: disabled
#
#- name: Set SELinux in permissive mode until the machine is rebooted
#  command: setenforce 0
#  ignore_errors: true
#  changed_when: false

- name: Install EPEL release for nginx
  yum: name=epel-release state=present

- name: Install nginx web server
  yum: name=nginx state=installed update_cache=true

- name: Copy Nginx metric generator script
  copy:
    src: "opt/prometheus/make_nginx_config.py"
    dest: "/opt/prometheus/make_nginx_config.py"
    owner: "root"
    mode: 0700

- name: Copy Nginx config reload script
  copy:
    src: "opt/prometheus/refresh_nginx_config.sh"
    dest: "/opt/prometheus/refresh_nginx_config.sh"
    owner: "root"
    mode: 0700

- name: Copy Nginx config
  copy:
    src: "etc/nginx/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    mode: 0700
  notify:
    - Start nginx

- name: Create cron to generate configs
  cron:
    name: "Install refresh nginx proxy config cron job"
    user: "root"
    job: "/opt/prometheus/refresh_nginx_config.sh"
    cron_file: nginx-metrics-proxy

- name: Remove MAILTO from cron
  lineinfile:
    path: /etc/crontab
    state: absent
    regexp: '^MAILTO'